In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X', 'Y'])


In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [15]:
dframe1

X         Y         Z
0 -0.183717 -1.696715 -1.586252
1  0.770807  0.097251  1.569509
2 -0.727315 -0.227842 -0.910366
3 -0.815299  1.336746  0.703243

In [16]:
dframe2

Y         Q         X
0 -0.056100  0.530380 -2.456004
1  0.411753 -0.796285  0.836234
2 -0.333170 -0.619868 -0.144034

In [17]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN -0.183717 -1.696715 -1.586252
1       NaN  0.770807  0.097251  1.569509
2       NaN -0.727315 -0.227842 -0.910366
3       NaN -0.815299  1.336746  0.703243
0  0.530380 -2.456004 -0.056100       NaN
1 -0.796285  0.836234  0.411753       NaN
2 -0.619868 -0.144034 -0.333170       NaN

In [18]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.183717 -1.696715 -1.586252
1       NaN  0.770807  0.097251  1.569509
2       NaN -0.727315 -0.227842 -0.910366
3       NaN -0.815299  1.336746  0.703243
4  0.530380 -2.456004 -0.056100       NaN
5 -0.796285  0.836234  0.411753       NaN
6 -0.619868 -0.144034 -0.333170       NaN

In [19]:
pd.concat([dframe1, dframe2], axis = 1)

X         Y         Z         Y         Q         X
0 -0.183717 -1.696715 -1.586252 -0.056100  0.530380 -2.456004
1  0.770807  0.097251  1.569509  0.411753 -0.796285  0.836234
2 -0.727315 -0.227842 -0.910366 -0.333170 -0.619868 -0.144034
3 -0.815299  1.336746  0.703243       NaN       NaN       NaN